### PR TITLE
UTD-1558 Add NET_EXCESS_GENERATION ChargeType

### PR DESCRIPTION
**Pull request by ArulmozhiAvinash**
Add  NET_EXCESS_GENERATION ChargeType in factory utils to add support for NEM3 Credits in TeamTariff

### CODE REVIEW

**Comment by ArulmozhiAvinash** [comment]
The integration test wrt to the "rest/public/properties/lookups" seems to be failing due to a gateway timeout error will look into hence converting the PR from "Ready" to "Draft"

**Comment by ArulmozhiAvinash** [comment]
It seems there's an ongoing issue with the "public/properties/lookups" endpoint and the endpoint fails to run irrespective of the parameters that we pass. This has to be fixed from the API backend and this has been logged in this JIRA: https://arcadiapower.atlassian.net/browse/GEN-3711 hence marking this as Ready To Review state

**Comment by rchristy0** [comment]
the lookups failing to load is a known issue, but according to that ticket it should only occur if there is no filtering (or insufficient filtering). in other words, if we add some sort of filtering (e.g. using a specific key) to that call, it should work. If things are not working at all **irrespective** of the parameters, that may indicate something else is going on. 

Also in the latest build there are 2 test failures. the lookup test, but also the ones added in this PR. (looks like maybe the last commit changed the transaction type without updating the test)

**Review by rchristy0 — CHANGES_REQUESTED** [review]
Test failures. One (lookups) we may have to ack and let slide, but the other should be fixed before merging

**Comment by ArulmozhiAvinash** [comment]
> Test failures. One (lookups) we may have to ack and let slide, but the other should be fixed before merging

@rchristy0 Can we disable the lookup test failure with a note and follow-up task to enable it once when the endpoint has been fixed?

**Comment by rchristy0** [comment]
> > Test failures. One (lookups) we may have to ack and let slide, but the other should be fixed before merging
> 
> @rchristy0 Can we disable the lookup test failure with a note and follow-up task to enable it once when the endpoint has been fixed?

Yeah, that should be okay for now. put a TODO comment on the test with a reference the GEN ticket, and also cross-reference and comment on the GEN ticket that we had to hide a test in the js sdk

**Comment by ArulmozhiAvinash** [comment]
> the lookups failing to load is a known issue, but according to that ticket it should only occur if there is no filtering (or insufficient filtering). in other words, if we add some sort of filtering (e.g. using a specific key) to that call, it should work. If things are not working at all **irrespective** of the parameters, that may indicate something else is going on.
> 
> Also in the latest build there are 2 test failures. the lookup test, but also the ones added in this PR. (looks like maybe the last commit changed the transaction type without updating the test)



> > > Test failures. One (lookups) we may have to ack and let slide, but the other should be fixed before merging
> > 
> > 
> > @rchristy0 Can we disable the lookup test failure with a note and follow-up task to enable it once when the endpoint has been fixed?
> 
> Yeah, that should be okay for now. put a TODO comment on the test with a reference the GEN ticket, and also cross-reference and comment on the GEN ticket that we had to hide a test in the js sdk

@rchristy0 I have disabled the test case for now. We can enable it once when the endpoint gets fixed. I have also added a subtask to the original defect so that we can have track of it(https://arcadiapower.atlassian.net/browse/GEN-3881)

**Review by rchristy0 — APPROVED** [review]

**Pull request merged**
